total_price=input("how much was the meal?\n")
total_num_people=input("how many people is the bill split between?\n")
tip=input("how much would you like to leave as a tip?\n")
price=float(total_price)
np=int(total_num_people)
tp=float(tip)
total= (price/np)+(price*(tp/100))
#print(round(total,2))
print("Your cost is: "+ str(round(total,3))+"$")
